import { z } from "zod"

export const updateProfileSchema = z.object({
  culturalBackground: z.array(z.string()).optional(),
  dietaryRestrictions: z.array(z.string()).optional(),
  activityLevel: z.enum(["sedentary", "light", "moderate", "active"]).optional(),
  healthGoals: z.array(z.string()).optional(),
  favoriteFoods: z.array(z.string()).optional(),
  breakfastFoods: z.array(z.string()).optional(),
  lunchFoods: z.array(z.string()).optional(),
  dinnerFoods: z.array(z.string()).optional(),
  snackFoods: z.array(z.string()).optional(),
  notifications: z.boolean().optional(),
  dataSharing: z.boolean().optional(),
  units: z.enum(["metric", "imperial"]).optional(),
  breakfastReminderTime: z.string().regex(/^\d{2}:\d{2}$/).optional(),
  lunchReminderTime: z.string().regex(/^\d{2}:\d{2}$/).optional(),
  dinnerReminderTime: z.string().regex(/^\d{2}:\d{2}$/).optional(),
  weeklyCalorieTarget: z.number().min(500).max(10000).optional(),
  weeklyProteinTarget: z.number().min(10).max(500).optional(),
  weeklyExerciseDays: z.number().int().min(0).max(7).optional(),
  suggestedFoods: z.array(z.string()).optional(),
  avoidFoods: z.array(z.string()).optional(),
  mealPlanPreference: z.string().optional(),
  supplementSuggestions: z.array(z.string()).optional(),
})
